/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'newsletter-subscribers': NewsletterSubscriber;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navbar: Navbar;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (
    | AboutHeroBlock
    | AboutValuesBlock
    | AboutApproachBlock
    | AboutExpertiseBlock
    | AboutHobbiesBlock
    | AboutDuoBioBlock
    | AboutCollaborationBlock
    | AboutInstagramBlock
    | AboutCtaBlock
    | AboutNewsletterBlock
    | GalleryHeroBlock
    | GalleryGridBlock
    | GalleryQuoteBandBlock
    | GalleryFaqBlock
    | GalleryCtaBlock
    | GalleryNewsletterBlock
    | PolicyHeroBlock
    | PolicyContentBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock".
 */
export interface AboutHeroBlock {
  /**
   * Tekst wyświetlany jako okruszek nawigacyjny ponad nagłówkiem.
   */
  breadcrumbLabel?: string | null;
  heading: string;
  /**
   * Krótki akapit opisowy pod nagłówkiem.
   */
  lead?: string | null;
  primaryButton: {
    label: string;
    url: string;
    openInNewTab?: boolean | null;
  };
  portrait: number | Media;
  /**
   * Alternatywny opis zdjęcia portretowego (dla czytników ekranu i SEO). Jeśli puste, używany jest alt z kolekcji Media.
   */
  portraitAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutValuesBlock".
 */
export interface AboutValuesBlock {
  heading: string;
  lead?: string | null;
  photo: number | Media;
  photoAlt?: string | null;
  pillars?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutValues';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutApproachBlock".
 */
export interface AboutApproachBlock {
  heading: string;
  lead?: string | null;
  cards: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutApproach';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutExpertiseBlock".
 */
export interface AboutExpertiseBlock {
  heading: string;
  lead?: string | null;
  cards?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutExpertise';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHobbiesBlock".
 */
export interface AboutHobbiesBlock {
  heading: string;
  lead?: string | null;
  photo: number | Media;
  photoAlt?: string | null;
  imagePosition?: ('left' | 'right') | null;
  cards?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutHobbies';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutDuoBioBlock".
 */
export interface AboutDuoBioBlock {
  heading: string;
  lead?: string | null;
  subLead?: string | null;
  photo: number | Media;
  photoAlt?: string | null;
  cards?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutDuoBio';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCollaborationBlock".
 */
export interface AboutCollaborationBlock {
  heading: string;
  lead?: string | null;
  cards: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutCollaboration';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutInstagramBlock".
 */
export interface AboutInstagramBlock {
  heading: string;
  lead?: string | null;
  tiles?:
    | {
        photo: number | Media;
        photoAlt?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutInstagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCtaBlock".
 */
export interface AboutCtaBlock {
  heading: string;
  lead?: string | null;
  buttonLabel: string;
  buttonUrl: string;
  tone?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutNewsletterBlock".
 */
export interface AboutNewsletterBlock {
  heading: string;
  lead?: string | null;
  nameLabel?: string | null;
  emailLabel?: string | null;
  consentText: string;
  consentLinkLabel?: string | null;
  consentLinkUrl?: string | null;
  submitLabel: string;
  successMessage?: string | null;
  errorMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutNewsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryHeroBlock".
 */
export interface GalleryHeroBlock {
  breadcrumbLabel?: string | null;
  heading: string;
  lead?: string | null;
  categoryFilters?:
    | {
        label: string;
        /**
         * Musi pokrywać się ze slugiem kategorii w bloku 'Siatka zdjęć (Galeria)'
         */
        slug: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryGridBlock".
 */
export interface GalleryGridBlock {
  initialVisible?: number | null;
  loadMoreLabel?: string | null;
  emptyStateLabel?: string | null;
  photos: {
    image: number | Media;
    alt?: string | null;
    /**
     * Musi pokrywać się ze slugiem filtra w bloku 'Hero (Galeria)'
     */
    category: string;
    sortOrder?: number | null;
    captionTitle?: string | null;
    captionSubtitle?: string | null;
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryQuoteBandBlock".
 */
export interface GalleryQuoteBandBlock {
  photo: number | Media;
  photoAlt?: string | null;
  heading: string;
  lead: string;
  side?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryQuoteBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryFaqBlock".
 */
export interface GalleryFaqBlock {
  heading: string;
  lead?: string | null;
  items: {
    question: string;
    answer: string;
    defaultOpen?: boolean | null;
    id?: string | null;
  }[];
  contactBox: {
    heading: string;
    messageLabel?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryFaq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryCtaBlock".
 */
export interface GalleryCtaBlock {
  heading: string;
  lead?: string | null;
  buttonLabel: string;
  buttonUrl: string;
  tone?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryNewsletterBlock".
 */
export interface GalleryNewsletterBlock {
  heading: string;
  lead?: string | null;
  nameLabel?: string | null;
  emailLabel?: string | null;
  consentText: string;
  consentLinkLabel?: string | null;
  consentLinkUrl?: string | null;
  submitLabel: string;
  successMessage?: string | null;
  errorMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryNewsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyHeroBlock".
 */
export interface PolicyHeroBlock {
  breadcrumbLabel?: string | null;
  heading: string;
  /**
   * Wyświetlana pod nagłówkiem w formacie dd.MM.yyyy
   */
  lastUpdated?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'policyHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyContentBlock".
 */
export interface PolicyContentBlock {
  /**
   * Pełny tekst polityki prywatności. Dostępne: H2, H3, listy, pogrubienie, kursywa, linki, cytaty, separatory.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'policyContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  /**
   * Adres e-mail subskrybenta. Pole readOnly po pierwszym zapisie.
   */
  email: string;
  source?: ('footer' | 'landing' | 'import' | 'other') | null;
  /**
   * Czy subskrybent potwierdził zapis przez e-mail.
   */
  confirmed?: boolean | null;
  /**
   * Ustawiane automatycznie na serwerze przy zapisie.
   */
  consentGivenAt?: string | null;
  unsubscribedAt?: string | null;
  /**
   * Ustawiane automatycznie na serwerze przy zapisie.
   */
  ipAddress?: string | null;
  /**
   * Nagłówek User-Agent przeglądarki przy zapisie.
   */
  userAgent?: string | null;
  /**
   * Wewnętrzne notatki administratora.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        aboutHero?: T | AboutHeroBlockSelect<T>;
        aboutValues?: T | AboutValuesBlockSelect<T>;
        aboutApproach?: T | AboutApproachBlockSelect<T>;
        aboutExpertise?: T | AboutExpertiseBlockSelect<T>;
        aboutHobbies?: T | AboutHobbiesBlockSelect<T>;
        aboutDuoBio?: T | AboutDuoBioBlockSelect<T>;
        aboutCollaboration?: T | AboutCollaborationBlockSelect<T>;
        aboutInstagram?: T | AboutInstagramBlockSelect<T>;
        aboutCta?: T | AboutCtaBlockSelect<T>;
        aboutNewsletter?: T | AboutNewsletterBlockSelect<T>;
        galleryHero?: T | GalleryHeroBlockSelect<T>;
        galleryGrid?: T | GalleryGridBlockSelect<T>;
        galleryQuoteBand?: T | GalleryQuoteBandBlockSelect<T>;
        galleryFaq?: T | GalleryFaqBlockSelect<T>;
        galleryCta?: T | GalleryCtaBlockSelect<T>;
        galleryNewsletter?: T | GalleryNewsletterBlockSelect<T>;
        policyHero?: T | PolicyHeroBlockSelect<T>;
        policyContent?: T | PolicyContentBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHeroBlock_select".
 */
export interface AboutHeroBlockSelect<T extends boolean = true> {
  breadcrumbLabel?: T;
  heading?: T;
  lead?: T;
  primaryButton?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
      };
  portrait?: T;
  portraitAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutValuesBlock_select".
 */
export interface AboutValuesBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  photo?: T;
  photoAlt?: T;
  pillars?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutApproachBlock_select".
 */
export interface AboutApproachBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutExpertiseBlock_select".
 */
export interface AboutExpertiseBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutHobbiesBlock_select".
 */
export interface AboutHobbiesBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  photo?: T;
  photoAlt?: T;
  imagePosition?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutDuoBioBlock_select".
 */
export interface AboutDuoBioBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  subLead?: T;
  photo?: T;
  photoAlt?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCollaborationBlock_select".
 */
export interface AboutCollaborationBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutInstagramBlock_select".
 */
export interface AboutInstagramBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  tiles?:
    | T
    | {
        photo?: T;
        photoAlt?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutCtaBlock_select".
 */
export interface AboutCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutNewsletterBlock_select".
 */
export interface AboutNewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  nameLabel?: T;
  emailLabel?: T;
  consentText?: T;
  consentLinkLabel?: T;
  consentLinkUrl?: T;
  submitLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryHeroBlock_select".
 */
export interface GalleryHeroBlockSelect<T extends boolean = true> {
  breadcrumbLabel?: T;
  heading?: T;
  lead?: T;
  categoryFilters?:
    | T
    | {
        label?: T;
        slug?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryGridBlock_select".
 */
export interface GalleryGridBlockSelect<T extends boolean = true> {
  initialVisible?: T;
  loadMoreLabel?: T;
  emptyStateLabel?: T;
  photos?:
    | T
    | {
        image?: T;
        alt?: T;
        category?: T;
        sortOrder?: T;
        captionTitle?: T;
        captionSubtitle?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryQuoteBandBlock_select".
 */
export interface GalleryQuoteBandBlockSelect<T extends boolean = true> {
  photo?: T;
  photoAlt?: T;
  heading?: T;
  lead?: T;
  side?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryFaqBlock_select".
 */
export interface GalleryFaqBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        defaultOpen?: T;
        id?: T;
      };
  contactBox?:
    | T
    | {
        heading?: T;
        messageLabel?: T;
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryCtaBlock_select".
 */
export interface GalleryCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  tone?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryNewsletterBlock_select".
 */
export interface GalleryNewsletterBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  nameLabel?: T;
  emailLabel?: T;
  consentText?: T;
  consentLinkLabel?: T;
  consentLinkUrl?: T;
  submitLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyHeroBlock_select".
 */
export interface PolicyHeroBlockSelect<T extends boolean = true> {
  breadcrumbLabel?: T;
  heading?: T;
  lastUpdated?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PolicyContentBlock_select".
 */
export interface PolicyContentBlockSelect<T extends boolean = true> {
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  confirmed?: T;
  consentGivenAt?: T;
  unsubscribedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  layout?:
    | (
        | HomepageHeroBlock
        | HomepageIntroBlock
        | HomepageServicesBlock
        | HomepagePhilosophyBlock
        | HomepageGalleryBlock
        | HomepageProcessBlock
        | HomepageTestimonialsBlock
        | HomepageAboutTeaserBlock
        | HomepageInstagramBlock
        | HomepageCtaBlock
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock".
 */
export interface HomepageHeroBlock {
  photo: number | Media;
  heading: string;
  subheading?: string | null;
  primaryButton: {
    label: string;
    url: string;
  };
  secondaryButton?: {
    label?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageIntroBlock".
 */
export interface HomepageIntroBlock {
  heading: string;
  /**
   * Kursywny blok cytatu, np. "Asia, ja naprawdę nie umiem pozować"
   */
  pullQuote?: string | null;
  /**
   * Tekst główny sekcji (2–3 akapity). Dostępne: pogrubienie, kursywa.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Zdjęcie w stylu polaroidu po prawej stronie.
   */
  photo: number | Media;
  /**
   * Tekst w stylu odręcznym nakładany na polaroid, np. "I found a love for me…"
   */
  photoQuote?: string | null;
  /**
   * Tekst alternatywny zdjęcia dla czytników ekranu.
   */
  photoAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageIntro';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageServicesBlock".
 */
export interface HomepageServicesBlock {
  heading: string;
  subheading?: string | null;
  services: {
    photo: number | Media;
    title: string;
    description: string;
    linkUrl?: string | null;
    id?: string | null;
  }[];
  customSessionHeading?: string | null;
  customSessionText?: string | null;
  customSessionButtonLabel?: string | null;
  customSessionButtonUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageServices';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepagePhilosophyBlock".
 */
export interface HomepagePhilosophyBlock {
  heading: string;
  lead?: string | null;
  pillars: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepagePhilosophy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageGalleryBlock".
 */
export interface HomepageGalleryBlock {
  heading: string;
  subheading?: string | null;
  galleryLinkLabel?: string | null;
  galleryLinkUrl?: string | null;
  photos: {
    image: number | Media;
    captionTitle?: string | null;
    captionSubtitle?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageProcessBlock".
 */
export interface HomepageProcessBlock {
  heading: string;
  lead?: string | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  steps: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageProcess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTestimonialsBlock".
 */
export interface HomepageTestimonialsBlock {
  heading: string;
  testimonials: {
    quote: string;
    clientName: string;
    photo?: (number | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageTestimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutTeaserBlock".
 */
export interface HomepageAboutTeaserBlock {
  heading: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  linkLabel?: string | null;
  linkUrl?: string | null;
  photo: number | Media;
  photoAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageAboutTeaser';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageInstagramBlock".
 */
export interface HomepageInstagramBlock {
  heading: string;
  instagramHandle: string;
  instagramUrl: string;
  avatarImage?: (number | null) | Media;
  photos: {
    image: number | Media;
    linkUrl?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageInstagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageCtaBlock".
 */
export interface HomepageCtaBlock {
  heading: string;
  subheading?: string | null;
  buttonLabel: string;
  buttonUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homepageCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  logo?: (number | null) | Media;
  /**
   * Wyświetlane gdy logo nie jest ustawione (fallback wordmark)
   */
  logoLabel?: string | null;
  /**
   * Maksymalnie 8 pozycji
   */
  navItems?:
    | {
        label: string;
        /**
         * np. /oferta, /galeria
         */
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    openInNewTab?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo wyświetlane w stopce. Jeśli nie ustawione, zostanie użyty placeholder tekstowy.
   */
  logo?: (number | null) | Media;
  /**
   * Maksymalnie 6 linków do mediów społecznościowych.
   */
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'pinterest' | 'youtube' | 'other';
        url: string;
        /**
         * Tekst alternatywny / aria-label dla linku.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  columnServices?: {
    heading?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  columnSite?: {
    heading?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    consentText?: string | null;
  };
  /**
   * Użyj {{year}} jako placeholder dla bieżącego roku.
   */
  copyright?: string | null;
  /**
   * Np. Polityka prywatności, Ustawienia cookies.
   */
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        homepageHero?: T | HomepageHeroBlockSelect<T>;
        homepageIntro?: T | HomepageIntroBlockSelect<T>;
        homepageServices?: T | HomepageServicesBlockSelect<T>;
        homepagePhilosophy?: T | HomepagePhilosophyBlockSelect<T>;
        homepageGallery?: T | HomepageGalleryBlockSelect<T>;
        homepageProcess?: T | HomepageProcessBlockSelect<T>;
        homepageTestimonials?: T | HomepageTestimonialsBlockSelect<T>;
        homepageAboutTeaser?: T | HomepageAboutTeaserBlockSelect<T>;
        homepageInstagram?: T | HomepageInstagramBlockSelect<T>;
        homepageCta?: T | HomepageCtaBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageHeroBlock_select".
 */
export interface HomepageHeroBlockSelect<T extends boolean = true> {
  photo?: T;
  heading?: T;
  subheading?: T;
  primaryButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryButton?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageIntroBlock_select".
 */
export interface HomepageIntroBlockSelect<T extends boolean = true> {
  heading?: T;
  pullQuote?: T;
  body?: T;
  photo?: T;
  photoQuote?: T;
  photoAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageServicesBlock_select".
 */
export interface HomepageServicesBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  services?:
    | T
    | {
        photo?: T;
        title?: T;
        description?: T;
        linkUrl?: T;
        id?: T;
      };
  customSessionHeading?: T;
  customSessionText?: T;
  customSessionButtonLabel?: T;
  customSessionButtonUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepagePhilosophyBlock_select".
 */
export interface HomepagePhilosophyBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  pillars?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageGalleryBlock_select".
 */
export interface HomepageGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  galleryLinkLabel?: T;
  galleryLinkUrl?: T;
  photos?:
    | T
    | {
        image?: T;
        captionTitle?: T;
        captionSubtitle?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageProcessBlock_select".
 */
export interface HomepageProcessBlockSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageTestimonialsBlock_select".
 */
export interface HomepageTestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        clientName?: T;
        photo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageAboutTeaserBlock_select".
 */
export interface HomepageAboutTeaserBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  linkLabel?: T;
  linkUrl?: T;
  photo?: T;
  photoAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageInstagramBlock_select".
 */
export interface HomepageInstagramBlockSelect<T extends boolean = true> {
  heading?: T;
  instagramHandle?: T;
  instagramUrl?: T;
  avatarImage?: T;
  photos?:
    | T
    | {
        image?: T;
        linkUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomepageCtaBlock_select".
 */
export interface HomepageCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  logo?: T;
  logoLabel?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  columnServices?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  columnSite?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        placeholder?: T;
        buttonLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        consentText?: T;
      };
  copyright?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}