/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    offerItems: OfferItem;
    galleries: Gallery;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    offerItems: OfferItemsSelect<false> | OfferItemsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'pl' | 'pl'[];
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
    aboutPage: AboutPage;
    contactPage: ContactPage;
    privacyPolicyPage: PrivacyPolicyPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    privacyPolicyPage: PrivacyPolicyPageSelect<false> | PrivacyPolicyPageSelect<true>;
  };
  locale: 'pl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | HomeHeroBlock
    | IntroQuoteBlock
    | OfferShowcaseBlock
    | ProcessStepsBlock
    | HomeGalleryBlock
    | TestimonialBlock
    | HomeAboutBlock
    | HomeInstagramBlock
    | HomeCtaBlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  /**
   * Cztery linie tytułu hero. Linie 2 (italik) i 3 są wyróżnione kursywą serif.
   */
  title: {
    lineOne: string;
    lineTwoItalic: string;
    lineTwoRest: string;
    lineThree: string;
  };
  description: string;
  /**
   * Pełnoekranowe zdjęcie tła (poziome, min. 1920×1080).
   */
  background: number | Media;
  showScallop?: boolean | null;
  /**
   * Pierwszy przycisk renderowany jest jako pełny (primary). Drugi jako tekstowy ze strzałką (secondary).
   */
  ctas?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock".
 */
export interface IntroQuoteBlock {
  heading: {
    start: string;
    emphasis: string;
  };
  introLeadIn: string;
  /**
   * Wyróżniony cytat w ramce z dekoracyjnym znacznikiem cudzysłowu.
   */
  quoteText: string;
  body: string;
  collageImage: number | Media;
  collageImageAlt: string;
  /**
   * Wyświetlany jako odręczny napis na karteczce. Krótkie zdanie.
   */
  handwrittenQuote: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'introQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferShowcaseBlock".
 */
export interface OfferShowcaseBlock {
  heading: {
    start: string;
    emphasis: string;
    end: string;
  };
  subtitle: string;
  /**
   * Wybierz oferty wyświetlane w karuzeli. Kolejność ma znaczenie.
   */
  items: (number | OfferItem)[];
  inquiry: {
    title: string;
    text: string;
    cta?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  showFooterNotch?: boolean | null;
  /**
   * Jeśli pusta, użyta zostanie domyślna tekstura projektu.
   */
  backgroundTexture?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'offerShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offerItems".
 */
export interface OfferItem {
  id: number;
  /**
   * Np. „Sesja kobieca”. Używana w tytule karty, podstrony i SEO.
   */
  title: string;
  /**
   * Treść wyświetlana na karcie w sekcji oferty na stronie głównej (2–4 zdania).
   */
  shortDescription: string;
  /**
   * Zdjęcie karty (rekomendowany format pionowy 4:5 lub 2:3).
   */
  image: number | Media;
  /**
   * Opis alternatywny obrazu (dostępność, SEO). Najlepiej krótkie, opisowe zdanie.
   */
  imageAlt: string;
  /**
   * Opcjonalne klasy Tailwind do kadrowania obrazu na karcie (np. "h-[150%] top-[-16.62%] w-full"). Zostaw puste, by użyć domyślnego dopasowania cover.
   */
  imageCropClassName?: string | null;
  hero?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    description?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
    image?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    imageAlt?: string | null;
  };
  approach?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    introParagraph1?: string | null;
    introParagraph2?: string | null;
    /**
     * Dokładnie 3 bloki. Układ graficzny każdego bloku jest stały.
     */
    blocks?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    portraitImage?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    portraitAlt?: string | null;
  };
  packages?: {
    catalogDownload?: {
      label?: string | null;
      url?: string | null;
    };
    /**
     * Dokładnie 3 pakiety. Kolorystyka (sage/cream/rose) i kadrowanie są przypisane wg kolejności.
     */
    items?:
      | {
          image?: (number | null) | Media;
          /**
           * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
           */
          imageAlt?: string | null;
          title: string;
          /**
           * Tekst wyświetlany wprost, np. „750 zł”.
           */
          price: string;
          /**
           * Np. „Najczęściej wybierany”.
           */
          badgeLabel?: string | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  inclusions?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    intro?: string | null;
    /**
     * Maksymalnie 6 pozycji (przekrzywienia i ozdoby są przypisane wg kolejności).
     */
    checklist?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    accordionHeading?: string | null;
    accordion?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Same zdjęcia kolażu są elementem layoutu (w kodzie) — tu podajesz tylko opis alternatywny.
     */
    mainImageAlt?: string | null;
    scallopImageAlt?: string | null;
  };
  care?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    intro?: string | null;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    imageAlt?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  testimonial?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    items?:
      | {
          quote: string;
          author: string;
          photo?: (number | null) | Media;
          /**
           * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
           */
          photoAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  processSteps?: {
    heading?: {
      plain?: string | null;
      emphasis?: string | null;
    };
    intro?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
    /**
     * Numery kroków są nadawane automatycznie wg kolejności.
     */
    items?:
      | {
          title: string;
          paragraphs?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  gallery?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      /**
       * Opcjonalne — zostaw puste, jeśli nagłówek nie ma wyróżnionego fragmentu.
       */
      emphasis?: string | null;
    };
    description?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
    /**
     * Maksymalnie 5 zdjęć (układ kafelków jest stały).
     */
    items?:
      | {
          image?: (number | null) | Media;
          /**
           * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
           */
          imageAlt?: string | null;
          captionTitle?: string | null;
          captionSubtitle?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  closingCta?: {
    heading?: string | null;
    body?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  faq?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem — razem tworzą całość.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    intro?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock".
 */
export interface ProcessStepsBlock {
  /**
   * Naprzemienne fragmenty „italic — tekst” składają się na pełen tytuł sekcji.
   */
  heading: {
    italicOne: string;
    plainOne: string;
    italicTwo: string;
    plainTwo: string;
  };
  intro: {
    paragraphOne: string;
    paragraphTwo: string;
  };
  /**
   * Dekoracje (ornament botaniczny, kąt obrotu kart) przypisywane są automatycznie na podstawie kolejności kroku.
   */
  items?:
    | {
        title: string;
        paragraphOne: string;
        paragraphTwo: string;
        id?: string | null;
      }[]
    | null;
  showWaxStamp?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'processSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeGalleryBlock".
 */
export interface HomeGalleryBlock {
  heading: {
    start: string;
    emphasis: string;
  };
  description: string;
  /**
   * Wyświetlany jako "→" link w sekcji nagłówka.
   */
  cta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  /**
   * Środkowy slot zawsze jest renderowany jako duże zdjęcie z podpisem. Pozostałe są małymi miniaturami.
   */
  items?:
    | {
        image: number | Media;
        imageAlt: string;
        /**
         * Te pola są widoczne tylko gdy ten slot jest renderowany jako duży (środkowy). Dla pozostałych są ignorowane.
         */
        caption?: {
          title?: string | null;
          subtitle?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  /**
   * Nagłówek dzieli się na fragment regularny i wyróżniony italikiem ("Wasze słowa to moje" + "paliwo do działania").
   */
  heading: {
    start: string;
    emphasis: string;
  };
  /**
   * Karuzela cykluje po wszystkich opiniach w kolejności listy.
   */
  items?:
    | {
        /**
         * Polskie cudzysłowy („...") wpisywane ręcznie — komponent renderuje treść 1:1.
         */
        quote: string;
        author: string;
        /**
         * Wyświetlane w dekoracyjnym polaroidzie po prawej stronie sekcji.
         */
        photo?: (number | null) | Media;
        photoAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  showPolaroid?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeAboutBlock".
 */
export interface HomeAboutBlock {
  heading: {
    start: string;
    emphasis: string;
    end: string;
  };
  paragraphOne: string;
  paragraphTwo: string;
  portrait: number | Media;
  portraitAlt?: string | null;
  /**
   * Prowadzi zwykle do /o-mnie.
   */
  cta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeAbout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeInstagramBlock".
 */
export interface HomeInstagramBlock {
  heading: {
    plain: string;
    emphasis: string;
  };
  profile: {
    avatar?: (number | null) | Media;
    avatarAlt?: string | null;
    /**
     * URL zewnętrzny do profilu Instagram.
     */
    profileLink: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  /**
   * Dokładnie 5 postów. Kolejność odpowiada kolejności na stronie.
   */
  posts?:
    | {
        image: number | Media;
        imageAlt: string;
        /**
         * Bezpośredni URL posta. Gdy pusty — klika do profilu.
         */
        href?: string | null;
        /**
         * Tailwind klasy precyzującego kadrowanie zdjęcia w kafelku (np. "absolute h-[134%] top-[-0.5%]…"). Zostaw puste dla cover domyślnego.
         */
        cropClassName?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeInstagram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeCtaBlock".
 */
export interface HomeCtaBlock {
  heading: {
    plain: string;
    emphasis: string;
  };
  body: string;
  /**
   * Prowadzi zwykle do /kontakt.
   */
  cta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * Krótkie wprowadzenie do galerii (1–3 zdania).
   */
  intro?: string | null;
  coverImage: number | Media;
  /**
   * Galeria może być powiązana z konkretną usługą (np. sesja kobieca). Wyświetlana na podstronie oferty.
   */
  relatedOfferItem?: (number | null) | OfferItem;
  /**
   * Kolejność wpływa na układ w galerii. Każde zdjęcie wymaga osobnego opisu alt.
   */
  photos: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * Pierwszy ekran podstrony realizacji.
   */
  hero?: {
    /**
     * Zdanie podzielone na trzy części: początek, wyróżnienie i końcówka (np. kropka).
     */
    heading?: {
      lead?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    description?: string | null;
    backgroundImage?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    backgroundAlt?: string | null;
  };
  details?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    items?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  duoPerspective?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    leadParagraph?: string | null;
    callout?: string | null;
    photo?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    photoAlt?: string | null;
    highlights?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Te same trzy zdjęcia są używane na wszystkich szerokościach (desktop/tablet/mobile).
   */
  venueStory?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    body?: string | null;
    backImage?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    backAlt?: string | null;
    frontImage?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    frontAlt?: string | null;
    scallopImage?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    scallopAlt?: string | null;
  };
  /**
   * Same zdjęcia pochodzą z zakładki „Treść” → „Zdjęcia”. Tu ustawiasz tylko nagłówek i etykietę przycisku.
   */
  photoGallery?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    loadMoreLabel?: string | null;
  };
  testimonial?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    items?:
      | {
          quote?: string | null;
          author?: string | null;
          photo?: (number | null) | Media;
          /**
           * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
           */
          photoAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  memorableMoment?: {
    title?: string | null;
    body?: string | null;
    portraitPhoto?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    portraitAlt?: string | null;
    landscapePhoto?: (number | null) | Media;
    /**
     * Opis dla dostępności i SEO (krótkie, opisowe zdanie).
     */
    landscapeAlt?: string | null;
  };
  closingCta?: {
    /**
     * Jedno zdanie podzielone na części. „Wyróżnienie” jest renderowane innym krojem/kolorem.
     */
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    body?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'offerItems';
        value: number | OfferItem;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        homeHero?: T | HomeHeroBlockSelect<T>;
        introQuote?: T | IntroQuoteBlockSelect<T>;
        offerShowcase?: T | OfferShowcaseBlockSelect<T>;
        processSteps?: T | ProcessStepsBlockSelect<T>;
        homeGallery?: T | HomeGalleryBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        homeAbout?: T | HomeAboutBlockSelect<T>;
        homeInstagram?: T | HomeInstagramBlockSelect<T>;
        homeCta?: T | HomeCtaBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  title?:
    | T
    | {
        lineOne?: T;
        lineTwoItalic?: T;
        lineTwoRest?: T;
        lineThree?: T;
      };
  description?: T;
  background?: T;
  showScallop?: T;
  ctas?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock_select".
 */
export interface IntroQuoteBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        start?: T;
        emphasis?: T;
      };
  introLeadIn?: T;
  quoteText?: T;
  body?: T;
  collageImage?: T;
  collageImageAlt?: T;
  handwrittenQuote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OfferShowcaseBlock_select".
 */
export interface OfferShowcaseBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        start?: T;
        emphasis?: T;
        end?: T;
      };
  subtitle?: T;
  items?: T;
  inquiry?:
    | T
    | {
        title?: T;
        text?: T;
        cta?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  showFooterNotch?: T;
  backgroundTexture?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessStepsBlock_select".
 */
export interface ProcessStepsBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        italicOne?: T;
        plainOne?: T;
        italicTwo?: T;
        plainTwo?: T;
      };
  intro?:
    | T
    | {
        paragraphOne?: T;
        paragraphTwo?: T;
      };
  items?:
    | T
    | {
        title?: T;
        paragraphOne?: T;
        paragraphTwo?: T;
        id?: T;
      };
  showWaxStamp?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeGalleryBlock_select".
 */
export interface HomeGalleryBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        start?: T;
        emphasis?: T;
      };
  description?: T;
  cta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  items?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        caption?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        start?: T;
        emphasis?: T;
      };
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        photo?: T;
        photoAlt?: T;
        id?: T;
      };
  showPolaroid?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeAboutBlock_select".
 */
export interface HomeAboutBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        start?: T;
        emphasis?: T;
        end?: T;
      };
  paragraphOne?: T;
  paragraphTwo?: T;
  portrait?: T;
  portraitAlt?: T;
  cta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeInstagramBlock_select".
 */
export interface HomeInstagramBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        plain?: T;
        emphasis?: T;
      };
  profile?:
    | T
    | {
        avatar?: T;
        avatarAlt?: T;
        profileLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  posts?:
    | T
    | {
        image?: T;
        imageAlt?: T;
        href?: T;
        cropClassName?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeCtaBlock_select".
 */
export interface HomeCtaBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        plain?: T;
        emphasis?: T;
      };
  body?: T;
  cta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offerItems_select".
 */
export interface OfferItemsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  image?: T;
  imageAlt?: T;
  imageCropClassName?: T;
  hero?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  approach?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        introParagraph1?: T;
        introParagraph2?: T;
        blocks?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        portraitImage?: T;
        portraitAlt?: T;
      };
  packages?:
    | T
    | {
        catalogDownload?:
          | T
          | {
              label?: T;
              url?: T;
            };
        items?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              title?: T;
              price?: T;
              badgeLabel?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  inclusions?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        intro?: T;
        checklist?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        accordionHeading?: T;
        accordion?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        mainImageAlt?: T;
        scallopImageAlt?: T;
      };
  care?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        intro?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        image?: T;
        imageAlt?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  testimonial?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              photo?: T;
              photoAlt?: T;
              id?: T;
            };
      };
  processSteps?:
    | T
    | {
        heading?:
          | T
          | {
              plain?: T;
              emphasis?: T;
            };
        intro?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        items?:
          | T
          | {
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        items?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              captionTitle?: T;
              captionSubtitle?: T;
              id?: T;
            };
      };
  closingCta?:
    | T
    | {
        heading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  faq?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        intro?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  coverImage?: T;
  relatedOfferItem?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              emphasis?: T;
              end?: T;
            };
        description?: T;
        backgroundImage?: T;
        backgroundAlt?: T;
      };
  details?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  duoPerspective?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        leadParagraph?: T;
        callout?: T;
        photo?: T;
        photoAlt?: T;
        highlights?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  venueStory?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        body?: T;
        backImage?: T;
        backAlt?: T;
        frontImage?: T;
        frontAlt?: T;
        scallopImage?: T;
        scallopAlt?: T;
      };
  photoGallery?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        loadMoreLabel?: T;
      };
  testimonial?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              photo?: T;
              photoAlt?: T;
              id?: T;
            };
      };
  memorableMoment?:
    | T
    | {
        title?: T;
        body?: T;
        portraitPhoto?: T;
        portraitAlt?: T;
        landscapePhoto?: T;
        landscapeAlt?: T;
      };
  closingCta?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Centralne dane brandowe: kontakt, lokalizacje, social media oraz domyślny CTA. Używane w stopce i jako fallback w blokach contentowych.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  email?: string | null;
  phone?: string | null;
  /**
   * Krótki tekst typu "Kraków · Przemyśl i okolice" wyświetlany w stopce i przy CTA.
   */
  locationsLabel?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'pinterest' | 'youtube' | 'weselezklasa' | 'other';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wartości używane jako fallback w blokach (np. OfferShowcase) gdy redaktor pominie własny CTA.
   */
  inquiryDefaults?: {
    label?: string | null;
    url?: string | null;
  };
  newsletter: {
    heading?: {
      plain?: string | null;
      emphasis?: string | null;
      plainEnd?: string | null;
    };
    intro?: string | null;
    submitLabel?: string | null;
    /**
     * Wyświetlany jako "politykę prywatności" pod formularzem.
     */
    privacyLink: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label: string;
    };
    photo?: (number | null) | Media;
    photoAlt?: string | null;
  };
  /**
   * Bieżący rok zostanie wstawiony w miejsce literału `{year}`, np. "© {year} Oczki Fotografia".
   */
  copyright?: string | null;
  /**
   * Linki do podstron oferty wyświetlane w stopce.
   */
  serviceLinks?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Linki do pozostałych podstron wyświetlane w stopce.
   */
  pageLinks?:
    | {
        label: string;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Portfolio w stopce — od 4 do 6 zdjęć, wyświetlane jako siatka.
   */
  galleryImages?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Treść podstrony /o-mnie. Układ, ozdobniki botaniczne i piksele layoutu są zaszyte w kodzie — tu edytujesz tylko teksty i zdjęcia.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  hero?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    description?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
    portrait?: (number | null) | Media;
    portraitAlt?: string | null;
    secondaryPhoto?: (number | null) | Media;
    secondaryPhotoAlt?: string | null;
  };
  philosophy?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    intro?: string | null;
    principles?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  sessionFeel?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    intro?: string | null;
    /**
     * Kolejność jest istotna — numery kroków są generowane automatycznie.
     */
    steps?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  expertise?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
    };
    intro?: string | null;
    cards?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  beyond?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    intro?: string | null;
    backdrop?: (number | null) | Media;
    backdropAlt?: string | null;
    features?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  dual?: {
    /**
     * Ten nagłówek zaczyna się od wyróżnienia.
     */
    heading?: {
      emphasis?: string | null;
      end?: string | null;
    };
    intro?: string | null;
    portrait?: (number | null) | Media;
    portraitAlt?: string | null;
    profileHeading?: string | null;
    profileItems?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pillars?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    intro?: string | null;
    items?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  instagram?: {
    heading?: {
      plain?: string | null;
      emphasis?: string | null;
    };
    profileUrl?: string | null;
  };
  cta?: {
    /**
     * Jednozdaniowy nagłówek — brak podziału na wyróżnienie w tym komponencie.
     */
    headingText?: string | null;
    body?: string | null;
    button?: {
      label?: string | null;
      url?: string | null;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Treść podstrony /kontakt. Formularz, botanika i layout są zaszyte w kodzie — tu edytujesz tylko teksty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: number;
  hero?: {
    heading?: {
      start?: string | null;
      emphasis?: string | null;
      end?: string | null;
    };
    description?: string | null;
    sessionQuestion?: string | null;
    submitLabel?: string | null;
  };
  serviceArea?: {
    heading?: string | null;
    introParagraph1?: string | null;
    introParagraph2?: string | null;
    accordion?:
      | {
          id?: string | null;
          title?: string | null;
          body?: string | null;
        }[]
      | null;
    footer?: string | null;
    cta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  faq?: {
    /**
     * Ten nagłówek zaczyna się od wyróżnienia, po którym następuje reszta tekstu.
     */
    heading?: {
      emphasis?: string | null;
      start?: string | null;
    };
    intro?: string | null;
    items?:
      | {
          id?: string | null;
          question?: string | null;
          answer?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Treść podstrony /polityka-prywatnosci. Układ i ozdobniki są zaszyte w kodzie — tu edytujesz przepisy prawne.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicyPage".
 */
export interface PrivacyPolicyPage {
  id: number;
  pageTitle?: string | null;
  intro?: string | null;
  /**
   * Każda sekcja ma numer (generowany kolejnością), tytuł, opcjonalny wstęp, opcjonalną treść główną i opcjonalną listę punktowaną.
   */
  sections?:
    | {
        id?: string | null;
        title?: string | null;
        body?: string | null;
        intro?: string | null;
        bullets?:
          | {
              id?: string | null;
              title?: string | null;
              description?: string | null;
            }[]
          | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  locationsLabel?: T;
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  inquiryDefaults?:
    | T
    | {
        label?: T;
        url?: T;
      };
  newsletter?:
    | T
    | {
        heading?:
          | T
          | {
              plain?: T;
              emphasis?: T;
              plainEnd?: T;
            };
        intro?: T;
        submitLabel?: T;
        privacyLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        photo?: T;
        photoAlt?: T;
      };
  copyright?: T;
  serviceLinks?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  pageLinks?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  galleryImages?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        portrait?: T;
        portraitAlt?: T;
        secondaryPhoto?: T;
        secondaryPhotoAlt?: T;
      };
  philosophy?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        intro?: T;
        principles?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  sessionFeel?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  expertise?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
            };
        intro?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  beyond?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        intro?: T;
        backdrop?: T;
        backdropAlt?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  dual?:
    | T
    | {
        heading?:
          | T
          | {
              emphasis?: T;
              end?: T;
            };
        intro?: T;
        portrait?: T;
        portraitAlt?: T;
        profileHeading?: T;
        profileItems?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pillars?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        intro?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  instagram?:
    | T
    | {
        heading?:
          | T
          | {
              plain?: T;
              emphasis?: T;
            };
        profileUrl?: T;
      };
  cta?:
    | T
    | {
        headingText?: T;
        body?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?:
          | T
          | {
              start?: T;
              emphasis?: T;
              end?: T;
            };
        description?: T;
        sessionQuestion?: T;
        submitLabel?: T;
      };
  serviceArea?:
    | T
    | {
        heading?: T;
        introParagraph1?: T;
        introParagraph2?: T;
        accordion?:
          | T
          | {
              id?: T;
              title?: T;
              body?: T;
            };
        footer?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  faq?:
    | T
    | {
        heading?:
          | T
          | {
              emphasis?: T;
              start?: T;
            };
        intro?: T;
        items?:
          | T
          | {
              id?: T;
              question?: T;
              answer?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacyPolicyPage_select".
 */
export interface PrivacyPolicyPageSelect<T extends boolean = true> {
  pageTitle?: T;
  intro?: T;
  sections?:
    | T
    | {
        id?: T;
        title?: T;
        body?: T;
        intro?: T;
        bullets?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'offerItems';
          value: number | OfferItem;
        } | null)
      | ({
          relationTo: 'galleries';
          value: number | Gallery;
        } | null);
    global?: ('aboutPage' | 'contactPage' | 'privacyPolicyPage') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}